theme: jekyll-theme-cayman
title: "Portfolio Data Analyst – Ferial Zamoun"
description: "Transformation de données dispersées en décisions fiables | Python · Streamlit · Power BI · Machine Learning"
show_downloads: false
markdown: kramdown
kramdown:
  input: GFM
incremental: true
livereload: true

exclude:
  - .venv/
  - venv/
  - streamlit_app/
  - _site/
  - .vscode/
  - node_modules/
